# Generated by Django 4.2.3 on 2023-07-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_stock',
            field=models.CharField(choices=[('AC ROOM', 'AC ROOM'), ('NON AC ROOM', 'NON AC ROOM')], max_length=50),
        ),
    ]
