# Generated by Django 4.2.3 on 2023-07-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_room_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=255, null=True, upload_to='upload/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomimage', to='hotel.room')),
            ],
        ),
    ]
