# Generated by Django 4.2.3 on 2023-07-26 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0003_remove_room_room_image_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
                ('check_in', models.DateField(default=datetime.datetime.now, null=True)),
                ('check_out', models.DateField(default=datetime.datetime.now, null=True)),
                ('total_members', models.IntegerField()),
                ('status_type', models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED')], max_length=50)),
                ('total_amount', models.FloatField()),
                ('is_booking', models.BooleanField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
