# Generated by Django 4.2.3 on 2023-07-27 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_booking_is_booking_alter_booking_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.DateField(default=datetime.datetime.now, null=True)),
                ('check_out', models.DateField(default=datetime.datetime.now, null=True)),
                ('total_members', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
