# Generated by Django 4.2.3 on 2023-07-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_roomsearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomSearch',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_booking',
        ),
    ]
