# Generated by Django 4.2.3 on 2023-07-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_delete_roomsearch_remove_booking_is_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
