# Generated by Django 4.2.3 on 2023-07-29 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0009_booking_total_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('payemnt_type', models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('PAYTM', 'PAYTM')], max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=10, max_digits=15)),
                ('order_id', models.IntegerField(default=None, null=True, unique=True)),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
