# Generated by Django 4.2.3 on 2023-07-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('PAYTM', 'PAYTM')], max_length=30),
        ),
    ]
