# Generated by Django 4.2.3 on 2023-08-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_booking_user_alter_payment_payemnt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('PAYTM', 'PAYTM')], max_length=30),
        ),
    ]
