# Generated by Django 4.2.3 on 2023-08-06 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_alter_payment_payemnt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('PAYTM', 'PAYTM'), ('CARD', 'CARD'), ('CASH', 'CASH')], max_length=30),
        ),
    ]
