# Generated by Django 4.2.3 on 2023-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_payment_booking_alter_payment_payemnt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('PAYTM', 'PAYTM')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
