# Generated by Django 4.2.3 on 2023-08-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_alter_payment_payemnt_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('PAYTM', 'PAYTM')], max_length=30),
        ),
    ]
