# Generated by Django 4.2.3 on 2023-08-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_booking_booking_status_alter_payment_payemnt_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('PAYTM', 'PAYTM')], max_length=30),
        ),
    ]
