# Generated by Django 4.2.3 on 2023-08-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_alter_booking_room_alter_payment_payemnt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_room',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('CARD', 'CARD'), ('CASH', 'CASH'), ('PAYTM', 'PAYTM')], max_length=30),
        ),
    ]
