# Generated by Django 4.2.3 on 2023-08-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_booking_no_of_room_alter_payment_payemnt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('PAYTM', 'PAYTM'), ('CARD', 'CARD')], max_length=30),
        ),
    ]
