# Generated by Django 4.2.3 on 2023-08-22 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_alter_payment_payemnt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payemnt_type',
            field=models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('PAYTM', 'PAYTM')], max_length=30),
        ),
    ]
